RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_users.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_country.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_genre.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_movie.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_poster.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_review.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_movie_to_country.sql'
RUNSCRIPT FROM 'classpath:db/h2/ddl/create_table_movie_to_genre.sql'