language: java

addons:
  sonarcloud:
    projectKey: Metranik_movieland
    organization: metranik-github
    token:
      secure: 053d1965853a44cdc8f456ef294029cadc3a64a4
  
branches:
  only:
    - master
    
notifications: 
  email:
    recipients:
      - arttaraskin@gmail.com
    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always
     
deploy:
  provider: heroku
  api_key:
    secure: 3cbfa491-8c15-43da-b495-39ba64068955
  app: art-movieland  