language: java

branches:
  only:
    - master
    - ci-cd
    
notifications: 
  email:
    recipients:
      - arttaraskin@gmail.com
    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always