RUNSCRIPT FROM 'classpath:db/h2/data/data_users.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_country.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_genre.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_movie.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_poster.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_review.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_movie_to_country.sql'
RUNSCRIPT FROM 'classpath:db/h2/data/data_movie_to_genre.sql'